### ISSUE TITLE
Review code of copied "NFQ rules"

### ISSUE THREAD

**Issue by leebc** [aethelwulffe/PQRS_Gateway#10]
Some of the NFQ rules from the CQM report are rules that PQRS measures implement. 
I copied those NFQ_xxxx files into the PQRS rules directory and renamed the TOP LEVEL files to their PQRS name.  
 * I did not change any code.  
 * Classes, etc, may break if the file names have to match.
     - I'm pretty sure the report engine requires that the names of the files match the classes they contain.
 * The logic may not be correct.

---===>>>   Go through each of the PQRS_0* measures listed below.
*  Make sure the class names are correct.
*  Make sure the logic does is correct for what we need for the PQRS measure vs. what they needed for NQF.

	new file:   PQRS_0001.php
	new file:   PQRS_0001/Numerator.php
	new file:   PQRS_0001/PopulationCriteria.php
	new file:   PQRS_0066.php
	new file:   PQRS_0066/Denominator.php
	new file:   PQRS_0066/Exclusion.php
	new file:   PQRS_0066/InitialPatientPopulation.php
	new file:   PQRS_0066/Numerator.php
	new file:   PQRS_0066/PopulationCriteria.php
	new file:   PQRS_0110.php
	new file:   PQRS_0110/Denominator.php
	new file:   PQRS_0110/Exclusions.php
	new file:   PQRS_0110/InitialPatientPopulation.php
	new file:   PQRS_0110/Numerator.php
	new file:   PQRS_0110/PopulationCriteria.php
	new file:   PQRS_0111.php
	new file:   PQRS_0111/Denominator.php
	new file:   PQRS_0111/InitialPatientPopulation.php
	new file:   PQRS_0111/Numerator.php
	new file:   PQRS_0111/PopulationCriteria.php
	renamed:    NFQ_0421.php -> PQRS_0128.php
	renamed:    NFQ_0421/Denominator.php -> PQRS_0128/Denominator.php
	renamed:    NFQ_0421/Exclusion.php -> PQRS_0128/Exclusion.php
	renamed:    NFQ_0421/InitialPatientPopulation.php -> PQRS_0128/InitialPatientPopulation.php
	renamed:    NFQ_0421/InitialPatientPopulation2.php -> PQRS_0128/InitialPatientPopulation2.php
	renamed:    NFQ_0421/Numerator1.php -> PQRS_0128/Numerator1.php
	renamed:    NFQ_0421/Numerator2.php -> PQRS_0128/Numerator2.php
	renamed:    NFQ_0421/PopulationCriteria1.php -> PQRS_0128/PopulationCriteria1.php
	renamed:    NFQ_0421/PopulationCriteria2.php -> PQRS_0128/PopulationCriteria2.php
	new file:   PQRS_0154/Denominator.php
	new file:   PQRS_0154/DenominatorException.php
	new file:   PQRS_0154/InitialPatientPopulation.php
	new file:   PQRS_0154/Numerator.php
	new file:   PQRS_0154/PopulationCriteria.php

***Also note that***
	new file:   PQRS_0226 is NFQ_0028
[Issue #9 ](https://github.com/aethelwulffe/PQRS_Gateway/issues/9) is to identify and rename one of 3 NFQ_0028 rules to PQRS_0226.   Once these files are renamed, they need to be corrected too.

**Comment by leebc** [comment]
I just glanced at PQRS_0001 and the NFQ variant is not sufficient for what we need for PQRS.  PQRS is much more involved.

**Comment by aethelwulffe** [comment]
Looks like we are waaaay beyond this issue.  Another one closed!
