### ISSUE TITLE
Create a spreadsheet for rule building for Group Measures

### ISSUE THREAD

**Issue by meggerc** [aethelwulffe/PQRS_Gateway#15]
I'm posting this as a heads up and will work on this when the individual measure spreadsheets are completed. 

[2015_PQRS_MeasuresGroups_SingleSource_122214_v4.1.xlsx](https://github.com/aethelwulffe/PQRS_Gateway/files/148601/2015_PQRS_MeasuresGroups_SingleSource_122214_v4.1.xlsx)

**Comment by meggerc** [comment]
The group measures include individual measures AND also some measures that are not included with the individual measures.

**Comment by aethelwulffe** [comment]
Well, it looks like I will need that group measure specs to code for 
them, hunh?  I just though that groups were just groupings, not extra 
stuff too!  I guess I better get started on them.

**Comment by meggerc** [comment]
The group excel workbook I posted above has a separate worksheet for each group of measures, like DM for diabetes. Each worksheet includes the denominator codes for the group-only measures and the numerator HCPCS or CPT_II codes for the individual measures. Think over how you want to run these and I'll modify the excel workbook so it can be loaded. This is a clip of one of the worksheets:

![image](https://cloud.githubusercontent.com/assets/16786878/13443067/52f51860-dfcd-11e5-8cd9-1983022eb347.png)

**Comment by meggerc** [comment]
These might be helpful...
[Group measure flow charts.zip](https://github.com/aethelwulffe/PQRS_Gateway/files/153706/Group.measure.flow.charts.zip)

and here is the group measure manual
[2015_PQRS_MeasuresGroup_Manual_122214.pdf](https://github.com/aethelwulffe/PQRS_Gateway/files/153708/2015_PQRS_MeasuresGroup_Manual_122214.pdf)

**Comment by aethelwulffe** [comment]
Yes, very good reference.  Thank you!  It is really nice that you 
started this issue list, as I wasn't even aware this should be on the 
radar!  Now I know what to do with all my spare time!

**Comment by aethelwulffe** [comment]
This will be my morning work priority, right after checking in with Lou.

**Comment by meggerc** [comment]
@aethelwulffe I have the morning free on Friday. Can we meet? I have to head to Orlando in the afternoon for my son's wedding weekend.

**Comment by aethelwulffe** [comment]
Absolutely!
