### ISSUE TITLE
Individual Measures (For Groups) Creation/tracking

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#19]
A list of the measures in the measure groups that were missing from our "priority" measure list.
While awaiting the March 4 meetings and workgroups dealing with UI development and Measure group business logic, we are building out the code for those measures. (Stage 2 of individual measure creation).
  Stage 3 will be the measures that were not in our priority list, and were not in the measure groups (if any...but I imagine there are some.

**Comment by aethelwulffe** [comment]
Assuming that all active measures already have their codes in our tables (I finished the last domain spreadsheet conversion) then coding individual measures is pretty much a breeze.  Makes eyeballs bleed, but does not set the brain on fire.  If some of the measures for groups have not been done, then there is the issue of coding those.
If we had done the measures by group first, we would have had a lot easier time getting the codes for the denominators together, and with far less repetition.

**Comment by leebc** [comment]
Reviewed list of Measures present in Measure Groups; checked this against which measures we've created.  Below is a numerically sorted list of all Group Measure numbers.  Those with an "x" are Individual measures not created in our first pass of important measures.


0001	Diabetes: Hemoglobin A1c Poor Control
0005	Heart Failure (HF): Angiotensin-Converting Enzyme (ACE) Inhibitor or Angiotensin Receptor Blocker (ARB) Therapy for Left Ventricular Systolic Dysfunction (LVSD)
0006	Coronary Artery Disease (CAD): Antiplatelet Therapy
0007	Coronary Artery Disease (CAD): Beta-Blocker Therapy – Prior Myocardial Infarction (MI) or Left Ventricular Systolic Dysfunction (LVEF < 40%)
0008	Heart Failure (HF): Beta-Blocker Therapy for Left Ventricular Systolic Dysfunction (LVSD)
0039	Screening or Therapy for Osteoporosis for Women Aged 65 Years and Older
0043 x 	Coronary Artery Bypass Graft (CABG): Use of Internal Mammary Artery (IMA) in Patients with Isolated CABG Surgery
0044 x 	Coronary Artery Bypass Graft (CABG): Preoperative Beta-Blocker in Patients with Isolated CABG Surgery
0047	Care Plan
0048	Urinary Incontinence: Assessment of Presence or Absence of Urinary Incontinence in Women Aged 65 Years and Older
0051	Chronic Obstructive Pulmonary Disease (COPD): Spirometry Evaluation 
0052	Chronic Obstructive Pulmonary Disease (COPD): Inhaled Bronchodilator Therapy
0053	Asthma: Pharmacologic Therapy for Persistent Asthma - Ambulatory Care Setting
0071 x	Breast Cancer: Hormonal Therapy for Stage IC - IIIC Estrogen Receptor/Progesterone Receptor (ER/PR) Positive Breast Cancer
0072 x	Colon Cancer: Chemotherapy for AJCC Stage III Colon Cancer Patients
0084 x	Hepatitis C: Ribonucleic Acid (RNA) Testing Before Initiating Treatment
0085 x	Hepatitis C: HCV Genotype Testing Prior to Treatment
0087 x	Hepatitis C: Hepatitis C Virus (HCV) Ribonucleic Acid (RNA) Testing Between 4-12 Weeks After Initiation of Treatment
0091	Acute Otitis Externa (AOE): Topical Therapy 328
0093	Acute Otitis Externa (AOE): Systemic Antimicrobial Therapy – Avoidance of Inappropriate Use
0108 x	Rheumatoid Arthritis (RA): Disease Modifying Anti-Rheumatic Drug (DMARD)Therapy
0110	Preventive Care and Screening: Influenza Immunization
0110	Preventive Care and Screening: Influenza Immunization 197
0111	Pneumonia Vaccination Status for Older Adults
0112	Breast Cancer Screening
0113	Colorectal Cancer Screening
0117	Diabetes: Eye Exam
0119	Diabetes: Medical Attention for Nephropathy
0121	Adult Kidney Disease: Laboratory Testing (Lipid Profile)
0122	Adult Kidney Disease: Blood Pressure Management
0128	Preventive Care and Screening: Body Mass Index (BMI) Screening and Follow-Up Plan
0128	Preventive Care and Screening: Body Mass Index (BMI) Screening and Follow-Up Plan 68
0130	Documentation of Current Medications in the Medical Record
0130	Documentation of Current Medications in the Medical Record 10
0131	Pain Assessment and Follow-Up
0134	Preventive Care and Screening: Screening for Clinical Depression and Follow-Up Plan
0143 x	Oncology: Medical and Radiation – Pain Intensity Quantified
0144 x	Oncology: Medical and Radiation – Plan of Care for Pain
0154	Falls: Risk Assessment
0155	Falls: Plan of Care
0160 x	HIV/AIDS: Pneumocystis Jiroveci Pneumonia (PCP) Prophylaxis
0163	Diabetes: Foot Exam
0164 x 	Coronary Artery Bypass Graft (CABG): Prolonged Intubation
0165 x 	Coronary Artery Bypass Graft (CABG): Deep Sternal Wound Infection Rate
0166 x 	Coronary Artery Bypass Graft (CABG): Stroke
0167 x 	Coronary Artery Bypass Graft (CABG): Postoperative Renal Failure
0168 x 	Coronary Artery Bypass Graft (CABG): Surgical Re-Exploration
0173	Preventive Care and Screening: Unhealthy Alcohol Use - Screening
0176 x	Rheumatoid Arthritis (RA): Tuberculosis Screening
0177 x	Rheumatoid Arthritis (RA): Periodic Assessment of Disease Activity
0178	Rheumatoid Arthritis (RA): Functional Status Assessment
0179 x	Rheumatoid Arthritis (RA): Assessment and Classification of Disease Prognosis
0180 x	Rheumatoid Arthritis (RA): Glucocorticoid Management
0183 x	Hepatitis C: Hepatitis A Vaccination
0191 x	Cataracts: 20/40 or Better Visual Acuity within 90 Days Following Cataract Surgery
0192 x	Cataracts: Complications within 30 Days Following Cataract Surgery Requiring Additional Surgical Procedures
0205	HIV/AIDS: Sexually Transmitted Disease Screening for Chlamydia, Gonorrhea, and Syphilis
0226	Preventive Care and Screening: Tobacco Use: Screening and Cessation Intervention
0242	Coronary Artery Disease (CAD): Symptom Management
0270 x	Inflammatory Bowel Disease (IBD): Preventive Care: Corticosteroid Sparing Therapy
0271 x	Inflammatory Bowel Disease (IBD): Preventive Care: Corticosteroid Related Iatrogenic Injury – Bone Loss Assessment
0274 x	Inflammatory Bowel Disease (IBD): Testing for Latent Tuberculosis (TB) Before Initiating Anti-TNF (Tumor Necrosis Factor)Therapy
0275 x	Inflammatory Bowel Disease (IBD): Assessment of Hepatitis B Virus (HBV) Status Before Initiating Anti-TNF (Tumor Necrosis Factor) Therapy
0276 x	Sleep Apnea: Assessment of Sleep Symptoms
0277 x	Sleep Apnea: Severity Assessment at Initial Diagnosis
0278 x	Sleep Apnea: Positive Airway Pressure Therapy Prescribed
0279 x	Sleep Apnea: Assessment of Adherence to Positive Airway Pressure Therapy
0280 x	Dementia: Staging of Dementia
0281 x	Dementia: Cognitive Assessment
0282 x	Dementia: Functional Status Assessment
0283 x	Dementia: Neuropsychiatric Symptom Assessment
0284 x	Dementia: Management of Neuropsychiatric Symptoms
0285 x	Dementia: Screening for Depressive Symptoms
0286 x	Dementia: Counseling Regarding Safety Concerns
0287 x	Dementia: Counseling Regarding Risks of Driving
0288 x	Dementia: Caregiver Education and Support
0289 x	Parkinson’s Disease: Annual Parkinson’s Disease Diagnosis Review
0290 x	Parkinson’s Disease: Psychiatric Disorders or Disturbances Assessment
0291 x	Parkinson’s Disease: Cognitive Impairment or Dysfunction Assessment
0292 x	Parkinson’s Disease: Querying about Sleep Disturbances
0293 x	Parkinson’s Disease: Rehabilitative Therapy Options
0294 x	Parkinson’s Disease: Parkinson’s Disease Medical and Surgical Treatment Options Reviewed
0303 x	Cataracts: Improvement in Patient’s Visual Function within 90 Days Following Cataract Surgery
0304 x	Cataracts: Patient Satisfaction within 90 Days Following Cataract Surgery
0317	Preventive Care and Screening: Screening for High Blood Pressure and Follow-Up Documented 
0331	Adult Sinusitis: Antibiotic Prescribed for Acute Sinusitis (Appropriate Use)
0332	Adult Sinusitis: Appropriate Choice of Antibiotic: Amoxicillin Prescribed for Patients with Acute Bacterial Sinusitis (Appropriate Use)
0333	Adult Sinusitis: Computerized Tomography (CT) for Acute Sinusitis (Overuse)
0338 x	HIV Viral Load Suppression
0339 x	Prescription of HIV Antiretroviral Therapy
0340 x	HIV Medical Visit Frequency
0350 x	Total Knee Replacement: Shared Decision-Making: Trial of Conservative (Non-surgical) Therapy
0351 x	Total Knee Replacement: Venous Thromboembolic and Cardiovascular Risk Evaluation
0352 x	Total Knee Replacement: Preoperative Antibiotic Infusion with Proximal Tourniquet
0353 x	Total Knee Replacement: Identification of Implanted Prosthesis in Operative Report
0354 x	Anastomotic Leak Intervention
0355 x	Unplanned Reoperation within the 30 Day Postoperative Period
0356 x	Unplanned Hospital Readmission within 30 Days of Principal Procedure
0357 x	Surgical Site Infection (SSI)
0358	Patient-Centered Surgical Risk Assessment and Communication
0359 x	Optimizing Patient Exposure to Ionizing Radiation: Utilization of a Standardized Nomenclature for Computed Tomography (CT) Imaging Description
0360 x	Optimizing Patient Exposure to Ionizing Radiation: Count of Potential High Dose Radiation Imaging Studies: Computed Tomography (CT) and Cardiac Nuclear Medicine Studies
0361 x	Optimizing Patient Exposure to Ionizing Radiation: Reporting to a Radiation Dose Index Registry
0362 x	Optimizing Patient Exposure to Ionizing Radiation: Computed Tomography (CT) Images Available for Patient Follow-up and Comparison Purposes
0363 x	Optimizing Patient Exposure to Ionizing Radiation: Search for Prior Computed Tomography (CT) Studies Through a Secure, Authorized, Media-Free, Shared Archive
0364 x	Optimizing Patient Exposure to Ionizing Radiation: Appropriateness: Follow-up CT Imaging for Incidentally Detected Pulmonary Nodules According to Recommended Guidelines
0388 x	Cataract Surgery with Intra-Operative Complications (Unplanned Rupture of Posterior Capsule Requiring Unplanned Vitrectomy)
0389 x	Cataract Surgery: Difference Between Planned and Final Refraction
0390	Discussion and Shared Decision Making Surrounding Treatment Options
0401	Screening for Hepatocellular Carcinoma (HCC) in Patients with Hepatitis C Cirrhosis
0402 x	Tobacco Use and Help with Quitting Among Adolescents

**Comment by aethelwulffe** [comment]
I have the initial patient population queries for all measure groups done.  That is 90% of the logic for the denominators for all of the measures in the groups.  Some of the groups have denominators that must have gender, age, and sometimes other checks in each measure for applicability, but that is only a few of them.
  Aside from that, the numerators are very easy.  That amounts to another 6-8 hours of work to finish the measure groups.  Since I already have about 600 hours in this project, that makes it seem trivial.

**Comment by aethelwulffe** [comment]
All measure groups for 2015 are coded and in the bag.
