### ISSUE TITLE
I don't know how to spell PQRS! 

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#2]
It always says 7777 when I type it on my phone.
![scc_pqrs_system](https://cloud.githubusercontent.com/assets/553751/12627788/cde4feda-c50d-11e5-96e4-1c734677993f.png)

**Comment by leebc** [comment]
PQRS is spelled PQRS.

Try installing mod-perl on  your phone for greatest versatility.

**Comment by FloydERoberts3** [comment]
Yes but on your phone you can spell it backwards !
