### ISSUE TITLE
Review of CDR API

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#3]
http://www.open-emr.org/apidocs/dev/OpenEMR/_library---clinical_rules.php.html
I imagine this auto-generated API is a bit out of date, but between that and digging through the code base, we should be able to generate a set of file locations for everything.
Interface/reports/cqm.php is a great place to start.  There is a lot under /custom as well as under /library/classes
/interface/super/rules
and of course here is the best one of all...
http://www.open-emr.org/wiki/index.php/2013_Ophthalmologist's_Meaningful_Use_Attestation#Additional_Measures_-_Conventional_Method

**Comment by aethelwulffe** [comment]
https://sourceforge.net/p/openemr/discussion/202504/thread/c9366c5d/
More on a current bug that may interfere with using the GUI to configure things.  That said, fixing it will make things a LOT less confusing.  For out in-house code, we can add some context instructions  to help keep us going.

**Comment by leebc** [comment]
interface/reports/cqm.php  -- Seems to be the UI for the report setup and display page for CQM and AMC.  lets the user choose settings for the particular report.  Validates form data.  Calls library/ajax/execute_cdr_report.php to run the report.  Generates a unique report ID and runs  library/ajax/status_report.php with that ID every 10 seconds to poll status and displays any updates.   Facilitates report download when finished.

We will likely modify this file and add our report generation to it, or copy this file to a new one and modify it to just run our report.  (leebc prefers second option.)

**Comment by aethelwulffe** [comment]
I do too.

**Comment by leebc** [comment]
library/ajax/execute_cdr_report.php -- Checks values, sets some values, then calls the function test_rules_clinic_batch_method($provider,$rule_filter,$array_date,"report",$plan_filter,$organize_method,$options,$pat_prov_rel,'',$_POST['execute_report_id']); from library/clinical_rules.php

**Comment by leebc** [comment]
library/clinical_rules.php --* Clinical Decision Rules(CDR) engine functions.*  Of particular interest to us is 
test_rules_clinic_batch_method, which does end up calling a bunch of other stuff as it batches through the patients, providers, and rules.

function listingCDRReminderLog($begin_date='',$end_date='') {

function clinical_summary_widget($patient_id,$mode,$dateTarget='',$organize_mode='default',$user='') {

  // Compare the current with most recent action log (this function will also log the current actions)
function active_alert_summary($patient_id,$mode,$dateTarget='',$organize_mode='default',$user='',$test=FALSE) {

  // Compare the current with most recent action log (this function will also log the current actions)
function allergy_conflict($patient_id,$mode,$user,$test=FALSE) {

 * Also functions to log the actions.
function compare_log_alerts($patient_id,$current_targets,$category='clinical_reminder_widget',$userid='',$log_trigger='all') {

function test_rules_clinic_batch_method($provider='',$type='',$dateTarget='',$mode='',$plan='',$organize_mode='default',$options=array(),$pat_prov_rel='primary',$batchSize='',$report_id=NULL) {

  // of planned batches(note the fixed array will go into the test_rules_clinic function, however the original will be used
function test_rules_clinic($provider='',$type='',$dateTarget='',$mode='',$patient_id='',$plan='',$organize_mode='default',$options=array(),$pat_prov_rel='primary',$start=NULL,$batchSize=NULL,$user='') {

function buildPatientArray($patient_id='',$provider='',$pat_prov_rel='primary',$start=NULL,$batchSize=NULL,$onlyCount=FALSE) {

function test_filter($patient_id,$rule,$dateTarget) {

function returnTargetGroups($rule) {

function test_targets($patient_id,$rule,$group_id='',$dateTarget) {

 * Function to return active plans
function resolve_plans_sql($type='',$patient_id='0',$configurableOnly=FALSE) {

 * Function to return a specific plan
function collect_plan($plan,$patient_id='0') {

 * Function to set a specific plan activity for a specific patient
function set_plan_activity_patient($plan,$type,$setting,$patient_id) {

 * Function to return active rules
function resolve_rules_sql($type='',$patient_id='0',$configurableOnly=FALSE,$plan='',$user='') {

 * Function to return a specific rule
function collect_rule($rule,$patient_id='0') {

 * Function to set a specific rule activity for a specific patient
function set_rule_activity_patient($rule,$type,$setting,$patient_id) {

 * Function to return applicable reminder dates (relative)
function resolve_reminder_sql($rule,$reminder_method) {

 * Function to return applicable filters
function resolve_filter_sql($rule,$filter_method,$include_flag=1) {

 * Function to return applicable targets
function resolve_target_sql($rule,$group_id='',$target_method,$include_flag=1) {

 * Function to return applicable actions
function resolve_action_sql($rule,$group_id='') {

 * Function to check database filters and targets
function database_check($patient_id,$filter,$interval='',$dateTarget='') {

 * Function to check procedure filters and targets
function procedure_check($patient_id,$filter,$interval='',$dateTarget='') {

 * Function to check for appointment
function appointment_check($patient_id,$dateTarget='') {

 * Function to check lists filters and targets. Customizable and currently includes diagnoses, medications, allergies and surgeries.
function lists_check($patient_id,$filter,$dateTarget) {

 * Function to check for existance of data in database for a patient
function exist_database_item($patient_id,$table,$column='',$data_comp,$data='',$num_items_comp,$num_items_thres,$intervalType='',$intervalValue='',$dateTarget='') {

 * Function to check for existence of procedure(s) for a patient
function exist_procedure_item($patient_id,$proc_title,$proc_code,$result_comp,$result_data='',$num_items_comp,$num_items_thres,$intervalType='',$intervalValue='',$dateTarget='') {

 * Function to check for existance of data for a patient in the rule_patient_data table
function exist_custom_item($patient_id,$category,$item,$complete,$num_items_comp,$num_items_thres,$intervalType='',$intervalValue='',$dateTarget) {

 * Function to check for existance of data for a patient in lifestyle section
function exist_lifestyle_item($patient_id,$lifestyle,$status,$dateTarget) {

 * Function to check for lists item of a patient. Fully customizable and includes diagnoses, medications,
function exist_lists_item($patient_id,$type,$value,$dateTarget) {

 * Function to return part of sql query to deal with interval  (Date stuff)
function sql_interval_string($table,$intervalType,$intervalValue,$dateTarget) {

 * Function to collect generic column labels from tables. It currently works for date
function collect_database_label($label,$table) {

 * Simple function to avoid processing of duplicate actions
function is_duplicate_action($actions,$action) {

 * This function returns an array that contains three elements (each element is a date).
function calculate_reminder_dates($rule, $dateTarget='',$type) {

function reminder_results_integrate($reminderOldArray, $reminderNew) {

function itemsNumberCompare($comp, $thres, $num_items) {

function convertCompSql($comp) {

 * Function to find age in years (with decimal) on the target date
function convertDobtoAgeYearDecimal($dob,$target) { 

 * Function to find age in months (with decimal) on the target date
function convertDobtoAgeMonthDecimal($dob,$target) {

 * Function to calculate the percentage for reports.
function calculate_percentage($pass_filt,$exclude_filt,$pass_targ) {

**Comment by aethelwulffe** [comment]
Hell of a good day's work leebc!

**Comment by leebc** [comment]
Working in my development instance:  https://pippin/aw1-openemr/
* Added  to library/globals.inc.php
     Global configuration options for PQRS
* Added to main/left_nav.php
          `<?php // 2016-02-02 leebc -- Adding menu section for PQRS ?>
     <?php if ($GLOBALS['enable_pqrs']) {?>
     <li><a class="collapsed_lv2"><span><?php xl('PQRS','e') ?></span></a>
       <ul>
          <?php genMiscLink('RTop','rep','0',xl('Physician Quality Reporting System -- Measures (Development stub)'),'reports/pqrs.php?type=standard'); ?>
          <?php genMiscLink('RTop','rep','0',xl('PQRS Measure Groups (Development stub)'),'reports/pqrs.php?type=groups'); ?>
        </ul>
  <?php }?>`

**Comment by leebc** [comment]
At this point, do we prefer the menu read:
* Physician Quality Reporting System -- Measures 
* Physician Quality Reporting System -- Measure Groups
or
* PQRS -- Measures
* PQRS -- Measure Groups

**Comment by Lanadot** [comment]
PQRS is fine with me.

**Comment by leebc** [comment]
interface/reports/cqm.php is called in:
* interface/main/left_nav.php:      #known
* interface/reports/cqm.php:         link_report = "cqm.php?report_id="+report_id;
* interface/reports/cqm.php:         //$('#status_span').replaceWith("<a id='view_button' href='cqm.php?report_id="+report_id+"' class='css_button' onclick='top.restoreSession()'><span><?php echo xlt('View Report'); ?></span></a>");
* interface/reports/cqm.php:   <form method='post' name='theform' id='theform' action='cqm.php?type=<?php echo attr($type_report) ;?>' onsubmit='return validateForm()'>
* interface/reports/report_results.php:    $link="cqm.php?report_id=" . attr($row["report_id"]) . "&back=list";
* interface/main/finder/patient_select.php:   <a href='../../reports/cqm.php?report_id=<?php echo attr($report_id) ?>' class='css_button' onclick='top.restoreSession()'><span><?php echo xlt("Return To Report Results"); ?></span></a>


Creating new branch. Copied interface/reports/cqm.php to interface/reports/pqrs.php and repaced instances of cqm.php with pqrs.php (there were 2 of them)

**Comment by aethelwulffe** [comment]
Library/classes/rulesets are the key.  Defining NFQ directories to include in the new xml output with >only< our up-to-date clean rulesets seems to make sense to me.  A version of "cqm.php" (perhaps called "PQRS.php" that cleanly reports and exports based on our rules and restricts to the valid options for reporting also seems to make sense to me.  The naming conventions like NFQ_0028_2014 mixed in with everything else is bothersome.  Not that we couldn't deal with it, but if we are configuring about a thousand new files under hundreds of new directories, then it will be a lot easier on us if they are not mixed with legacy code.

**Comment by leebc** [comment]
**interface/main/left_nav.php**
calls
**interface/reports/cqm.php**
which calls
**library/ajax/execute_cdr_report.php**
which calls
**library/clinical_rules.php** function **test_rules_clinic_batch_method** 
with arguments:
test_rules_clinic_batch_method($provider,$rule_filter,$array_date,"report",$plan_filter,$organize_method,$options,$pat_prov_rel,'',$_POST['execute_report_id']);
which calls the function
test_rules_clinic($provider,$type,$dateTarget,$mode,'',$plan,$organize_mode,$options_modified,$pat_prov_rel,(($batchSize*$i)+1),$batchSize);
which calls itself recursively
and (somewhere) looks at the rules and says:
    // If using cqm or amc type, then use the hard-coded rules set.
    // Note these rules are only used in report mode.
and it loads
 library/classes/rulesets/ReportManager.php
and runs
runReport( $rowRule, $patientData, $dateArray, $options );
which  require_once()
library/classes/rulesets/ReportTypes.php
and  __construct() and require_once()
library/classes/rulesets//library/*.php
library/classes/rulesets//Cqm/*.php
library/classes/rulesets//Amc/*.php
and then does the object thing with
new CqmReportFactory()   or   new AmcReportFactory() 
 from  
library/classes/rulesets/Cqm/CqmReportFactory.php or library/classes/rulesets/Amc/AmcReportFactory.php
These include the files from 
library/classes/rulesets/Amc/reports and library/classes/rulesets/Amc/library
or
library/classes/rulesets/Cqm/library/ and library/classes/rulesets/Cqm/reports/

**Comment by leebc** [comment]
**SO**
**library/classes/rulesets/ReportTypes.php** lists the rules that exist as files/objects  in **library/classes/rulesets/Amc/reports** and **library/classes/rulesets/Amc/library** or **library/classes/rulesets/Cqm/library/** and **library/classes/rulesets/Cqm/reports/**

**Comment by aethelwulffe** [comment]
So now we have a test rule running on dev, right?  Is that going into a branch?

**Comment by teryhill** [comment]
Is this going to be PQRS stand alone or is it in fact a Gateway.
Terry

**Comment by aethelwulffe** [comment]
Gateway++ if we understand what we are doing.
   We have a data import tool in the works to pull in claims data to act 
as a basis for providers to use the report engine (with or without using 
openemr themselves) to view, tweak and run their PQRS report 
generation.  For existing users, this just means an up-to-date PQRS 
simple xml version registry submission report generator.  For the 2015 
reports, we are doing as many measures as we can (meaning those we must) 
as we have only until March 31 to get those actually submitted.  For 
2016, a once-again revised and expanded measure (rule) set for all 
measures, and then of course be ready to dump all of that for the newer 
MIPS version.

**Comment by aethelwulffe** [comment]
Got a rundown from Sam tonight.  He has (almost) completely mapped out the flowchart of the entire rules engine and reporting system!  To print it, you would need some VERY BIG paper.  There are a few little pieces missing, but not stuff that seems all that relevant to what we are doing.  On the basis of that status, he is moving to the front-end portion of the project.  He is looking to have a solid start on the front end UI within a couple of days.  Things are going to move forward fast.

**Comment by aethelwulffe** [comment]
This issue is closed.  We are (semi) functioning!
