### ISSUE TITLE
Repo is messed up...

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#5]
We need to revert the merge I did with the upstream master.  Not sure how I managed that exactly.  Thought I was feeding it properly, but things got goofy.  That is my Git technospeak.
  I know I need a git revert -m, but I would like assistance to make things easy on the other branches.

**Comment by tmccormi** [comment]
I can fix it if you have the code change in a local branch to push afterwards.  You need to create a development project "release branch" and do your features in a feature branch to be merged into the release branch when ready (via pull request).

Always keep the "master" branch are refection of the upstream openemr master branch

**Comment by aethelwulffe** [comment]
I thought that the only commit to the master was a merge from 
501(c)3...  That was caused by me once again not knowing what the hell 
to do.  Yes, we also need to publish an integration branch and release 
branch

**Comment by aethelwulffe** [comment]
What I did was obviously not a re-base.  It appears to me that there are 
no commits of the group's code to the master.  If I am not wrong, please 
do what needs be done.  If I am wrong, I think we have all of what 
passes for "code" elsewhere and can re-publish it.

**Comment by tmccormi** [comment]
This is the diff between openemr upstream and this master branch
https://github.com/aethelwulffe/PQRS_Gateway/commit/8b02efb8830a5eb61aeb20b6ba5b68b5decca667

**Comment by aethelwulffe** [comment]
None of it is ours.  I have no idea what the heck happened here.
Please destroy whatever is going on here.  I will not attempt to feed 
master again without an armed and hostile supervisor in attendance.

**Comment by tmccormi** [comment]
Done.
tony@dragonfire:/opt/gitrepos/PQRS_Gateway (master)$ git pull upstream master
From github.com:oemr501c3/openemr
 * branch            master     -> FETCH_HEAD
Already up-to-date.
tony@dragonfire:/opt/gitrepos/PQRS_Gateway (master)$ git push -f origin master
Counting objects: 4085, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1389/1389), done.
Writing objects: 100% (1967/1967), 16.34 MiB | 2.81 MiB/s, done.
Total 1967 (delta 1127), reused 1302 (delta 463)
To git@github.com:aethelwulffe/PQRS_Gateway.git
 + 8b02efb...58955f6 master -> master (forced update)

**Comment by leebc** [comment]
Thanks for getting this fixed for us @tmccormi !
