### ISSUE TITLE
Claims2OEMR import tool

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#7]
https://github.com/aethelwulffe/PQRS_Gateway/tree/Claims2OEMR_scripts
Current Status:
2016FEB14
All features currently implemented pass quality checks with initial test data with OpenEMR code, and doing a 1.5 MB set of claims produced by GatewayEDI.

Current features
Output tables are:
x12 partners
Insurance_companies
facilities
addresses
phone_numbers
users
groups
patient_data
insurance_data
forms (linking form_encounter)
form_encounter (holds basic billing data with `reason` set to "Imported Encounter")
billing

TODO:

- [x]  Fix compound diagnosis pointer parsing in segment SV1

- [x]   De-kludge the single ST loop system.

- [x]  priority Add taxonomy codes (PRV Segment) to users

- [x]  Add billing codes to encounter description

- [ ]  Add scraped procedure codes to "codes" table, hopefully with a lookup for description if a good data source can be found.  Match to ICD10 existing as well.

- [ ]   Pull the maximum amount of data out of REF and other segments, such as contact data.

- [ ]   Add the claim files to the AR Session and set billing table status to "billed" etc...

- [ ]   Improve the state saving feature  and test with running multiple batches of files for the use of the EMR as an intermediary database or claim processing tool.

- [ ]   Use multi-threading more heavily.  Currently only the base engine uses mulit-threading, not the parsing code itself. 

- [ ] The functions all run in a single step.  Breaking it into multiple steps will allow a progress bar to work, among other things.  This approach was used for the first iteration to allow the scripts to be ported to PHP more easily, but doing so will improve performance beyond it's current awesomeness

**Comment by aethelwulffe** [comment]
After some goofiness involving initializing variables as a string type by assigning them like
variable = " "; with a space...
Then trying to compare values if(variable != "") without a space....
I managed to get output to the following tables concerning insurance companies:
`insurance_companies`
`addresses`
`phone_numbers`
-All with successful quality output linking them all to the `x12_partners` table.
Next up:
`patient_data`
`insurance_data` (patient insurance records linked to all above)
`billing`
`form_encounter`
`forms`
`users`
`groups`
`users_secure`
`user_preferences`
`codes`
`lists`....and a ton more, with the above being the highest priority.

**Comment by aethelwulffe** [comment]
Not trying to do medications and the like yet, as they are not as likely to be in the billing except in rare cases.  Users_secure and user_preferences need to hang on until I have a "this always works" set of tables for a user.  Currently you must update the password of an imported user to get them straightened out.  Existing users are unlikely to get overwritten, as the users table is using the provider's NPI instead of a simple increment index.  patient_data and all other tables are using a simple increment, as there are no guaranteed unique identifiers in the claim files.  Matching is done by arrays of strings stored in a global.  The contents of the strings are the unique combinations of the whole record content.  Insurance companies are matched on their CMS ID and other fields + their address data. Simply looking at the CMS ID is not sufficient.

**Comment by aethelwulffe** [comment]
Testing with output from Gateway EDI claims has issues.
After adding a button for "single ST-SE mode" and tweaking that to a working point...AND ensuring that secondary insurance companies that do not have the required CMS ID designated (which is an input file quality issue) do not cause the program to crash, I still seem to have failed to allow for compound diagnosis code justification.  Unfortunately, this means that the method I used to parse multiple modifiers is therefore broken.
Secondary payers without CMS ID's are now skipped instead of breaking the code.  We still want to tweak this a bit better.
Fixed billing table output for lines with CPT codes (was dropping a single quote).
Posting new Beta version by midnight (13FEB) that CAN consume GatewayEDI files.

**Comment by aethelwulffe** [comment]
WooHoo!
I now process even really bad files that are missing required elements.  Also, the Gateway EDI files I am testing sometimes have random line returns that were screwing with stuff, so now we even all that out before processing.
  For the files that are missing elements like an insurance company CMS ID, you get a warning message, but the program does not break in a messy fashion.
Version 1.3 Beta is published for download by contributors.

**Comment by aethelwulffe** [comment]
Fixed a half-dozen or so errors with formatting of the sql queries when attempting to get them to load into OpenEMR.  Just a lot of dumb mistakes from late-night coding.  Also discovered that the last time I ran it, there had been memory leaks due to previous runs where it had crashed.  Ran it today and it did the whole year's worth of data in a little more than 30 seconds, where it took four minutes previously.
  Unfortunately, mysql kept crapping on itself trying to import a 290k file.  It think this is due to the off-the-shelf pre-configured xampp package, and not an issue with the queries. 
  I have clean files, and we will try to import them onto a gimli VM once bclee is available.

**Comment by leebc** [comment]
Do you want an install of our PQRS_Gateway repo?   I can setup a third instance of openemr on pippin (for ease) or set you up on merry.   (Possibly Sunday, Probably Monday.)

**Comment by aethelwulffe** [comment]
Yeah, we can try it out on Monday or so.
   Gives us a "real" database to punch rules against too.  It's got to 
be very restricted access...as all of it is.

**Comment by aethelwulffe** [comment]
On to version 1.5 Beta.
Improvements:  Fully escape/sanitize all single quotes after compiling each file into a single string.
Insert ST-SE segments so that the current business logic still works with "good" files.
Fixed numerous SQL errors.
Added random time to date of service to (hopefully) prevent issues with the triple-unique key table insurance_data.  Issues are created when someone corrects an insurance (like wrong gender) after billing, then resubmits the same day.

**Comment by aethelwulffe** [comment]
Version 1.6 Beta has been functional for a while now.  Closing this issue.
