### ISSUE TITLE
Determine which NQF 0028 variant PQRS 226 uses

### ISSUE THREAD

**Issue by leebc** [aethelwulffe/PQRS_Gateway#9]
PQRS measure 226 **is** NFQ_0028.

I copied **library/classes/rulesets/Cqm/reports/NFQ_0028*/** to **library/classes/rulesets/PQRS/reports/**
  (Note that original creator **Incorrectly** named these files "NFQ*" instead of "NQF*")

However, there are 3 versions in this directory: 
**.../Cqm/reports/NFQ_0028_2014.php**,
**.../Cqm/reports/NFQ_0028b.php**, and
**.../Cqm/reports/NFQ_0028a.php**
(Plus a directory to go with each.)

This measure/rule deals with tobacco counseling and stop smoking aids.

---===>>>  Determine which of these variants is correct (I think it's probably the 2014 version).
-=> Rename **NFQ_0028xxxxx.php** to **PQRS_0226.php**
-=> Rename **NFQ_0028xxxxx/** to **PQRS_0226/**

**Comment by leebc** [comment]
The correct fix for this may be to scrap the whole thing and write it from scratch.

**Comment by samlikins** [comment]
I've felt the same way about the whole OpenEMR system on too many
occasions; but from my experience I've learned that, in time crunch
situations, modification to the existing system is far less expensive than
rebuilding it.  I feel the pain, I truly do!  What is it that you want to
scrap, and why do you think it should be rebuilt?


Sam Likins

WSI-Services
Owner / Creative Developer
Making Things Work
*727.490.WSIS (9747)*

**Comment by aethelwulffe** [comment]
Pretty sure he is referencing individual rules.
Many (or all) of them are very badly written.  Really badly.  I don't 
mean to hack on the guys at Ensoftec, far from it, but in review the 
ways they are getting data break easily and are way more complex than is 
necessary.  For instance, the check if something is an office visit, 
they don't look in the encounter to look for the place of service code 
(looking for an "11"), they make joins to look up a calendar category 
called "Office Visit" (which is user-configurable, and is often not used 
at all), then do string matches and a ton of other unnecessary stuff.
   Many of the queries are similar.  There are joins where they are not 
only totally unnecessary, but also mean that they become broken when 
someone adds an appointment category that is also POS code 11 (but named 
differently) or change the name of the calendar category.
